### PR TITLE
sdm710-common: Switch to OSS audio HAL

### PR DESCRIPTION
**Pull request by NaassomDourado**

### CODE REVIEW

**Comment by ivecera** [comment]
Hmm, I don't see this as a valid PR...

1. Switch to OSS audio
2. Revert it
3. Revert blobs
4. Add screen off fod that is unsupported on LOS
5. Enable it

 WTF is it? This PR should be about OSS audio switch...

**Comment by NaassomDourado** [comment]
> Hmm, I don't see this as a valid PR...
> 
> 1. Switch to OSS audio
> 2. Revert it
> 3. Revert blobs
> 4. Add screen off fod that is unsupported on LOS
> 5. Enable it
> 
> WTF is it? This PR should be about OSS audio switch...

I only made PR for switch to oss audio

**Comment by ivecera** [comment]
Look at attached commit

**Comment by uixdess** [comment]
We will review switching to OSS audio HAL later.
As I know, it will broke proximity on devices with Ultrasound proximity.

**Comment by ivecera** [comment]
Agree with Alex.

**Comment by NaassomDourado** [comment]
Also it is not needed now, since we have good and working vendor audio. Considered it only to solve broken audio.

**Comment by uixdess** [comment]
OSS is better if it didnt cause any issues

**Pull request closed without merging**
